import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { CREATE_HREF, GENERATE_HREF, HERO_CARDS, HERO_PROMPTS, HERO_VIDEO_SRC, HOW_PANEL_SRC, LANDING_ANNOUNCE, LONGFORM_DEMO_START, SHORTS_CARDS, SHORTS_PROMPTS, SHOWCASE_CARDS, THUMBNAIL_DEMO_SRC, landingPoster, landingVideo } from '../lib/landing-media.js'

const html = readFileSync(new URL('../home/index.html', import.meta.url), 'utf8')

test('hero video constant stays on R2', () => {
  assert.equal(HERO_VIDEO_SRC, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/VidsoHeroVideo.mp4')
  assert.equal(CREATE_HREF, '/signup')
  assert.equal(GENERATE_HREF, '/video-generation')
  assert.equal(THUMBNAIL_DEMO_SRC, '')
})

test('hero cards use landing placeholder URLs and keep a long/short mix', () => {
  assert.ok(HERO_CARDS.length >= 8)
  assert.ok(HERO_CARDS.every((c) => c.src && c.poster && c.file))
  const longs = HERO_CARDS.filter((c) => c.type === 'long')
  const shorts = HERO_CARDS.filter((c) => c.type === 'short')
  assert.ok(longs.length >= 5)
  assert.ok(shorts.length >= 3)
  assert.deepEqual(HERO_CARDS.map((c) => c.aspect), ['16:9', '9:16', '16:9', '16:9', '9:16', '16:9', '16:9', '9:16'])
  assert.deepEqual(HERO_CARDS.map((c) => c.label), ['Documentary', 'Shorts', 'Explainer', 'Listicle', 'Shorts', 'Story', 'History', 'Shorts'])
  assert.equal(HERO_PROMPTS.length, 8)
  assert.match(HERO_PROMPTS[0], /airport secrets/)
  assert.ok(HERO_CARDS.every((c) => /\/landing\/hero-card-\d\d\.mp4$/.test(c.src)))
  assert.ok(HERO_CARDS.every((c) => /\/landing\/hero-card-\d\d\.jpg$/.test(c.poster)))
  assert.equal(landingVideo('hero-card', 1), HERO_CARDS[0].src)
  assert.equal(landingPoster('hero-card', 1), HERO_CARDS[0].poster)
})

test('showcase is long-form only and shorts cards stay blank-ready', () => {
  assert.ok(SHORTS_CARDS.length >= 9)
  assert.ok(SHORTS_CARDS.every((c) => c.src && c.poster && c.category))
  assert.ok(SHORTS_CARDS.every((c) => /\/landing\/shorts-card-\d\d\.mp4$/.test(c.src)))
  assert.ok(SHOWCASE_CARDS.length >= 4)
  assert.ok(SHOWCASE_CARDS.every((c) => /videocarousel\d+\.mp4$/.test(c.src)))
  assert.ok(SHOWCASE_CARDS.every((c) => c.prompt && c.prompt.length > 12))
  assert.ok(SHOWCASE_CARDS.every((c) => c.category !== 'SHORT'))
  assert.equal(SHOWCASE_CARDS[0].category, 'DOCUMENTARY')
  assert.equal(SHORTS_PROMPTS.length, 8)
  assert.ok(SHORTS_PROMPTS.every((s) => s.length > 8 && /[a-zA-Z]$/.test(s)))
  assert.equal(HOW_PANEL_SRC, '')
})

test('hero pin transition is gone', () => {
  assert.ok(!html.includes('id="hero-pin"'))
  assert.ok(!html.includes('hero-dark-beat'))
  assert.ok(!html.includes('hero-pin-stage'))
  assert.ok(html.includes('id="demo-hero"'))
  const css = readFileSync(new URL('../home/landing-redesign.css', import.meta.url), 'utf8')
  assert.ok(!css.includes('--hero-pin-vh'))
  assert.ok(!css.includes('hero-pin-stage'))
})

test('landing keeps SEO, one H1, and nav anchors', () => {
  assert.match(html, /<meta name="description"/)
  assert.equal((html.match(/<h1[\s>]/g) || []).length, 1)
  for (const id of ['why-vidso', 'how', 'connect-claude', 'pricing', 'faq', 'ideas']) {
    assert.ok(html.includes(`id="${id}"`), id)
  }
  assert.ok(html.includes('Choose the plan for you.'))
  assert.ok(html.includes('What is Vidso?'))
  assert.ok(html.includes('Generate a Video Now'))
  assert.match(html, /hero-cta[\s\S]{0,180}btn-glow/)
  assert.ok(!html.includes('hero-pill'))
  assert.match(html, /Make any YouTube video[\s\S]{0,80}from a single idea/)
  assert.ok(html.includes('Your faceless YouTube'))
  assert.ok(html.includes('empire starts here'))
  assert.ok(html.includes('class="h1-mark"'))
  assert.ok(html.includes('class="nav-left"'))
  assert.ok(html.includes('id="hero-prompt"') || html.includes('hero-prompt'))
  assert.match(html, /action="\/video-generation"/)
  assert.ok(html.includes('Long Form Generator'))
  assert.ok(html.includes('Thumbnail Generator'))
  assert.ok(html.includes('Clipping'))
  assert.ok(!html.includes('Script to final cut'))
  assert.ok(!html.includes('id="hero-pin"'))
  assert.ok(html.includes('id="hero-prompt"'))
  assert.ok(html.includes('id="hero-marquee"'))
  assert.ok(html.includes('Trusted by creators building monetizable YouTube channels'))
  assert.ok(!html.includes('class="loved"'))
  assert.ok(!html.includes('Loved by creators'))
  assert.ok(!html.includes('Supported platform'))
  assert.ok(!html.includes('Turn any idea into a video'))
  assert.match(html, /Shorts from the[\s\S]{0,80}same idea/)
  assert.ok(html.includes('Long-form'))
  assert.ok(html.includes('Does Vidso support Shorts?'))
  assert.ok(html.includes('id="connect-claude"'))
  assert.ok(html.includes('Run Vidso from'))
  assert.ok(html.includes('See how it works'))
  assert.ok(html.includes('https://www.vidso.pro/mcp'))
  assert.ok(!html.includes('mcp-keys'))
  assert.ok(!html.includes('mcp-chat'))
  assert.ok(!html.includes('Connect Claude'))
  assert.ok(!html.includes('Claude AI video generator'))
  assert.ok(!html.includes('id="connect-stack"'))
  assert.ok(html.includes('claude-ai-icon.webp'))
  assert.ok(html.includes('openai-icon.svg'))
  assert.ok(html.includes('cursor-ai-code-icon.svg'))
  assert.ok(html.includes('kimi-ai-icon.svg'))
  assert.ok(!html.includes('&amp; CLI'))
  assert.ok(!html.includes('class="h1-swoosh"'))
  assert.ok(!html.includes('coming soon'))
  assert.ok(!html.includes('topo-bg'))
  assert.ok(!html.includes('demo-mute'))
  assert.ok(!html.includes('OpenArt'))
  assert.ok(!html.includes('10M+ creators'))
  assert.ok(!html.includes('Featured on'))
  assert.ok(html.includes('id="lp-announce"'))
  assert.ok(html.includes('id="lp-sitehead"'))
  assert.ok(html.includes('class="js-reveal"') || html.includes("classList.add('js-reveal')"))
  assert.ok(!html.includes('hero-ghost-cta'))
  assert.ok(html.includes('btn-label'))
  assert.ok(html.includes('transform="translate(1 0)"'))
  assert.ok(html.includes('class="ico-play"'))
})

test('landing reveal uses GSAP ScrollTrigger scrub instead of IntersectionObserver', () => {
  const reveal = readFileSync(new URL('../lib/landing-reveal.js', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../home/landing-redesign.css', import.meta.url), 'utf8')
  assert.ok(reveal.includes('scrub: 0.6'))
  assert.ok(reveal.includes('startAt(i === 0 ? 95 : 92)'))
  assert.ok(!reveal.includes('IntersectionObserver'))
  assert.ok(css.includes('.lp-sitehead'))
  assert.ok(css.includes('position:fixed'))
  assert.match(css, /\.rv-clip,\s*\.rv-line/)
  assert.ok(css.includes('.lp-red .results .eyebrow'))
  assert.ok(css.includes('.formats-float .formats-mid'))
  assert.ok(css.includes('.mcp-panel::after{display:none}'))
  assert.ok(css.includes('.lp-red .comp-cta::before{display:none}'))
  assert.ok(css.includes('.final-box::before{display:none}'))
  assert.ok(css.includes('.shorts-ico'))
  assert.ok(!css.includes('margin-top:-18px'))
})

test('announcement config and long-form demo start stay in one place', () => {
  assert.equal(LANDING_ANNOUNCE.key, 'announce_seedream5pro_v2')
  assert.equal(LANDING_ANNOUNCE.href, '/image-generation')
  assert.match(LANDING_ANNOUNCE.text, /Seedream 5.0 Pro/)
  assert.match(LANDING_ANNOUNCE.textMobile, /Thumbnail Generator/)
  assert.equal(LANDING_ANNOUNCE.cta, 'Try it now ›')
  assert.equal(LONGFORM_DEMO_START, 12)
})
