import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { CREATE_HREF, GENERATE_HREF, HERO_CARDS, HERO_PROMPTS, HERO_VIDEO_SRC, HOW_PANEL_SRC, LANDING_ANNOUNCE, LONGFORM_DEMO_START, SHORTS_CARDS, SHORTS_PROMPTS, SHOWCASE_CARDS, THUMBNAIL_DEMO_SRC } from '../lib/landing-media.js'

const html = readFileSync(new URL('../home/index.html', import.meta.url), 'utf8')

test('hero video constant stays on R2', () => {
  assert.equal(HERO_VIDEO_SRC, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/VidsoHeroVideo.mp4')
  assert.equal(CREATE_HREF, '/signup')
  assert.equal(GENERATE_HREF, '/dashboard')
  assert.equal(THUMBNAIL_DEMO_SRC, '')
})

test('hero cards use landing placeholder URLs and keep a long/short mix', () => {
  assert.ok(HERO_CARDS.length >= 8)
  assert.ok(HERO_CARDS.every((c) => c.src && c.file))
  const longs = HERO_CARDS.filter((c) => c.type === 'long')
  const shorts = HERO_CARDS.filter((c) => c.type === 'short')
  assert.ok(longs.length >= 5)
  assert.ok(shorts.length >= 3)
  assert.deepEqual(HERO_CARDS.map((c) => c.aspect), ['16:9', '9:16', '9:16', '9:16', '16:9', '16:9', '16:9', '16:9'])
  assert.deepEqual(HERO_CARDS.map((c) => c.label), ['Long-form', 'Short', 'Ad', 'UGC', 'Explainer', 'Product', 'Thumbnail', 'Voiceover'])
  assert.equal(HERO_PROMPTS.length, 8)
  assert.match(HERO_PROMPTS[0], /airport secrets/)
  const filled = Object.fromEntries(HERO_CARDS.map((c) => [c.label, c]))
  assert.equal(filled['Long-form'].src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpagelongform.mp4')
  assert.equal(filled.Short.src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpageshort.mp4')
  assert.equal(filled.UGC.src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpageugc.mp4')
  assert.equal(filled.Product.src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpageproduct.mp4')
  assert.equal(filled.Thumbnail.src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/thumbnail.png')
  assert.equal(filled.Thumbnail.poster, filled.Thumbnail.src)
  assert.equal(filled.Ad.src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpagead.mp4')
  assert.equal(filled.Explainer.src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/facelessstudio1.mp4')
  assert.equal(filled.Voiceover.src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/facelessstudio.mp4')
})

test('showcase mixes formats and format cards stay blank-ready', () => {
  assert.ok(SHORTS_CARDS.length >= 9)
  assert.ok(SHORTS_CARDS.every((c) => c.src && c.poster && c.category))
  assert.equal(SHORTS_CARDS.find((c) => c.slug === 'long-form').src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpageformatslongform.mp4')
  assert.equal(SHORTS_CARDS.find((c) => c.slug === 'shorts').src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpageformatsshort.mp4')
  assert.equal(SHORTS_CARDS.find((c) => c.slug === 'ads').src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpageformatsad.mp4')
  assert.equal(SHORTS_CARDS.find((c) => c.slug === 'ugc').src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpageformatsugc.mp4')
  assert.equal(SHORTS_CARDS.find((c) => c.slug === 'explainers').src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/facelessstudio3.mp4')
  assert.ok(SHORTS_CARDS.filter((c) => !['long-form', 'shorts', 'ads', 'ugc', 'explainers'].includes(c.slug)).every((c) => /\/landing\/format-card-[a-z0-9-]+\.mp4$/.test(c.src)))
  assert.ok(SHOWCASE_CARDS.length >= 4)
  assert.ok(SHOWCASE_CARDS.every((c) => /videocarousel\d+\.mp4$/.test(c.src)))
  assert.ok(SHOWCASE_CARDS.every((c) => c.prompt && c.prompt.length > 12))
  assert.ok(SHOWCASE_CARDS.some((c) => c.category === 'AD'))
  assert.ok(SHOWCASE_CARDS.some((c) => c.category === 'UGC'))
  assert.ok(SHOWCASE_CARDS.some((c) => c.category === 'PRODUCT'))
  assert.equal(SHOWCASE_CARDS[0].category, 'DOCUMENTARY')
  assert.equal(SHORTS_PROMPTS.length, 8)
  assert.ok(SHORTS_PROMPTS.every((s) => s.length > 8 && /[a-zA-Z]$/.test(s)))
  assert.equal(HOW_PANEL_SRC, '')
})

test('hero pin transition is gone', () => {
  assert.ok(!html.includes('id="hero-pin"'))
  assert.ok(!html.includes('hero-dark-beat'))
  assert.ok(!html.includes('hero-pin-stage'))
  assert.ok(!html.includes('id="demo-hero"'))
  assert.ok(!html.includes('id="demo-video"'))
  const css = readFileSync(new URL('../home/landing-redesign.css', import.meta.url), 'utf8')
  assert.ok(!css.includes('--hero-pin-vh'))
  assert.ok(!css.includes('hero-pin-stage'))
})

test('landing keeps SEO, one H1, and nav anchors', () => {
  assert.match(html, /<meta name="description"/)
  assert.equal((html.match(/<h1[\s>]/g) || []).length, 1)
  for (const id of ['why-vidso', 'how', 'connect-claude', 'pricing', 'faq', 'ideas']) {
    assert.ok(html.includes(`id="${id}"`), id)
  }
  assert.ok(html.includes('Choose the plan'))
  assert.ok(html.includes('for you.'))
  assert.ok(html.includes('What is Vidso?'))
  assert.ok(html.includes('Generate a Video Now'))
  assert.match(html, /hero-cta[\s\S]{0,180}btn-start/)
  assert.ok(!html.includes('hero-pill'))
  assert.match(html, /See what a single prompt[\s\S]{0,80}can make/)
  assert.ok(html.includes('Make '))
  assert.ok(html.includes('any video'))
  assert.ok(html.includes('you can imagine'))
  assert.ok(html.includes('class="h1-mark"'))
  const css = readFileSync(new URL('../home/landing-redesign.css', import.meta.url), 'utf8')
  assert.ok(css.includes('.hero-lp h1 .h1-mark::after'))
  assert.ok(html.includes('id="hero-prompt-mode"'))
  assert.ok(html.includes('id="top-models"'))
  assert.ok(html.includes('Browse all models'))
  assert.ok(html.includes('class="nav-left"'))
  assert.ok(html.includes('id="hero-prompt"') || html.includes('hero-prompt'))
  assert.match(html, /action="\/dashboard"/)
  assert.ok(html.includes('Long Form Generator'))
  assert.ok(html.includes('Thumbnail Generator'))
  assert.ok(html.includes('Clipping'))
  assert.ok(!html.includes('Script to final cut'))
  assert.ok(!html.includes('id="hero-pin"'))
  assert.ok(html.includes('id="hero-prompt"'))
  assert.ok(html.includes('id="hero-marquee"'))
  assert.ok(html.includes('Trusted by creators shipping videos from one workspace'))
  assert.ok(!html.includes('class="loved"'))
  assert.ok(!html.includes('Loved by creators'))
  assert.ok(!html.includes('Supported platform'))
  assert.ok(!html.includes('Turn any idea into a video'))
  assert.match(html, /Every kind of video[\s\S]{0,80}one workspace/)
  assert.ok(html.includes('Long-form'))
  assert.ok(html.includes('Does Vidso support Shorts?'))
  assert.ok(html.includes('id="connect-claude"'))
  assert.ok(html.includes('Run Vidso from'))
  assert.ok(html.includes('See how it works'))
  assert.ok(html.includes('https://www.vidso.pro/mcp'))
  assert.ok(html.includes('mcp-keys'))
  assert.ok(html.includes('mcp-panel'))
  assert.ok(html.includes('Copy the Vidso Connector URL'))
  assert.ok(!html.includes('mcp-chat'))
  assert.ok(!html.includes('Connect Claude'))
  assert.ok(!html.includes('Claude AI video generator'))
  assert.ok(!html.includes('id="connect-stack"'))
  assert.ok(html.includes('claude-ai-icon.webp'))
  assert.ok(html.includes('openai-icon.svg'))
  assert.ok(html.includes('cursor-ai-code-icon.svg'))
  assert.ok(html.includes('kimi-ai-icon.svg'))
  assert.ok(!html.includes('&amp; CLI'))
  assert.ok(!html.includes('class="h1-swoosh"'))
  assert.ok(!html.includes('id="studio-tools"'))
  assert.ok(!html.includes('Pick a live tool.'))
  assert.ok(!html.includes('Tools for'))
  assert.ok(!html.includes('topo-bg'))
  assert.ok(!html.includes('demo-mute'))
  assert.ok(!html.includes('OpenArt'))
  assert.ok(!html.includes('10M+ creators'))
  assert.ok(!html.includes('Featured on'))
  assert.ok(html.includes('id="lp-announce"'))
  assert.ok(html.includes('id="lp-sitehead"'))
  assert.ok(html.includes('class="js-reveal"') || html.includes("classList.add('js-reveal')"))
  assert.ok(!html.includes('hero-ghost-cta'))
  assert.ok(html.includes('btn-label'))
})

test('landing reveal uses GSAP ScrollTrigger scrub instead of IntersectionObserver', () => {
  const reveal = readFileSync(new URL('../lib/landing-reveal.js', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../home/landing-redesign.css', import.meta.url), 'utf8')
  assert.ok(reveal.includes('scrub: 0.6'))
  assert.ok(reveal.includes('startAt(i === 0 ? 95 : 92)'))
  assert.ok(!reveal.includes('IntersectionObserver'))
  assert.ok(css.includes('.lp-sitehead'))
  assert.ok(css.includes('position:fixed'))
  assert.match(css, /\.lp-red h1,[\s\S]*font-family:Satoshi/)
  assert.ok(!css.includes('.lp-red.is-home .lp-sitehead'))
  assert.ok(css.includes('.lp-red .lp-sitehead.is-scrolled'))
  assert.match(css, /\.rv-clip,\s*\.rv-line/)
  assert.ok(css.includes('.lp-red .results .eyebrow'))
  assert.ok(css.includes('.formats-float .formats-mid'))
  assert.ok(css.includes('.mcp-panel::after{display:none}'))
  assert.ok(css.includes('.lp-red .comp-cta::before{display:none}'))
  assert.ok(css.includes('.final-box::before{display:none}'))
  assert.ok(css.includes('.shorts-ico'))
  assert.ok(!css.includes('margin-top:-18px'))
})

test('FAQ accordion closes the open item across both columns', () => {
  const js = readFileSync(new URL('../lib/landing-page.js', import.meta.url), 'utf8')
  assert.match(js, /if \(single\) bindFaqSingle\(grid\)\s+else bindFaqGroup\(grid\)/)
  assert.ok(!js.includes("grid.querySelectorAll('.faq-col').forEach((col) => bindFaqGroup(col))"))
})

test('feature headings mark the important phrase in red', () => {
  assert.ok(html.includes('Run Vidso from your <span class="accent">AI agent</span>'))
  assert.ok(html.includes('Turn a topic into a <span class="accent">finished video</span>'))
  assert.ok(html.includes('Clips and Shorts from a <span class="accent">link or an idea</span>'))
  assert.ok(html.includes('Generate thumbnails from a <span class="accent">prompt</span>'))
  assert.ok(html.includes('Voiceover and captions in the <span class="accent">same pass</span>'))
  assert.ok(html.includes('Finish on a <span class="accent">multi-track timeline</span>'))
  assert.ok(html.includes('Choose the plan <span class="accent">for you.</span>'))
})

test('formats carousel only advances from arrows', () => {
  const js = readFileSync(new URL('../lib/landing-page.js', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../home/landing-redesign.css', import.meta.url), 'utf8')
  const shorts = js.slice(js.indexOf('function mountShorts'), js.indexOf('function mountShowcase'))
  assert.ok(!shorts.includes('pointerenter'))
  assert.ok(!shorts.includes('setInterval'))
  assert.ok(shorts.includes("querySelector('[data-short-prev]')"))
  assert.ok(css.includes('.shorts-nav:hover{background:#FE0C30'))
  assert.ok(css.includes('.shorts-nav{'))
})

test('UGC row plays looping ugcad clips in the vertical cards', () => {
  const js = readFileSync(new URL('../lib/landing-page.js', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../home/landing-redesign.css', import.meta.url), 'utf8')
  const attach = js.slice(js.indexOf('function attachUgcClip'), js.indexOf('function mountUgc'))
  assert.ok(attach.includes('v.loop = true'))
  assert.ok(attach.includes('v.autoplay = true'))
  assert.ok(attach.includes("v.setAttribute('muted', '')"))
  assert.ok(css.includes('object-fit:cover'))
  assert.ok(css.includes('.ugc-shot{') || css.includes('aspect-ratio:9/16'))
})

test('top-models copy is centered, heading wraps, and landing uses slots 1-10', () => {
  const css = readFileSync(new URL('../home/landing-redesign.css', import.meta.url), 'utf8')
  assert.match(css, /\.top-models-copy\{[\s\S]*?position:absolute[\s\S]*?left:50%[\s\S]*?top:50%[\s\S]*?transform:translate\(-50%,-50%\)/)
  assert.match(css, /\.lp-red\.is-home #connect-claude ~ #top-models h2\{[\s\S]*?white-space:normal;text-wrap:balance;text-align:center/)
  assert.ok(css.includes('.lp-red.is-home #top-models h2 .accent{display:block}'))
  assert.ok(css.includes('.top-models-tile[data-slot="10"]'))
  assert.ok(!css.includes('.top-models-tile[data-slot="11"]'))
  assert.ok(html.includes('landing-redesign.css?v=d1fbc'))
  assert.ok(html.includes('landing-page.js?v=d1fb5'))
})

test('announcement config and long-form demo start stay in one place', () => {
  assert.equal(LANDING_ANNOUNCE.key, 'announce_seedream5pro_v2')
  assert.equal(LANDING_ANNOUNCE.href, '/dashboard')
  assert.match(LANDING_ANNOUNCE.text, /Seedream 5.0 Pro/)
  assert.match(LANDING_ANNOUNCE.textMobile, /Thumbnail Generator/)
  assert.equal(LANDING_ANNOUNCE.cta, 'Try it now ›')
  assert.equal(LONGFORM_DEMO_START, 12)
})
