import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { CREATE_HREF, GENERATE_HREF, HERO_CARDS, HERO_PROMPTS, HERO_VIDEO_SRC, HOW_PANEL_SRC, LANDING_ANNOUNCE, LONGFORM_DEMO_START, SHORTS_CARDS, SHORTS_PROMPTS, SHOWCASE_CARDS, THUMBNAIL_DEMO_SRC } from '../lib/landing-media.js'

const html = readFileSync(new URL('../home/index.html', import.meta.url), 'utf8')

test('hero video constant stays on R2', () => {
  assert.equal(HERO_VIDEO_SRC, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/VidsoHeroVideo.mp4')
  assert.equal(CREATE_HREF, '/signup')
  assert.equal(GENERATE_HREF, '/dashboard')
  assert.equal(THUMBNAIL_DEMO_SRC, '')
})

test('hero cards use landing placeholder URLs and keep a long/short mix', () => {
  assert.ok(HERO_CARDS.length >= 8)
  assert.ok(HERO_CARDS.every((c) => c.src && c.file))
  const longs = HERO_CARDS.filter((c) => c.type === 'long')
  const shorts = HERO_CARDS.filter((c) => c.type === 'short')
  assert.ok(longs.length >= 5)
  assert.ok(shorts.length >= 3)
  assert.deepEqual(HERO_CARDS.map((c) => c.aspect), ['16:9', '9:16', '9:16', '9:16', '16:9', '16:9', '16:9', '16:9'])
  assert.deepEqual(HERO_CARDS.map((c) => c.label), ['Long-form', 'Short', 'Ad', 'UGC', 'Explainer', 'Product', 'Thumbnail', 'Voiceover'])
  assert.equal(HERO_PROMPTS.length, 8)
  assert.match(HERO_PROMPTS[0], /airport secrets/)
  const filled = Object.fromEntries(HERO_CARDS.map((c) => [c.label, c]))
  assert.equal(filled['Long-form'].src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpagelongform.mp4')
  assert.equal(filled.Short.src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpageshort.mp4')
  assert.equal(filled.UGC.src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpageugc.mp4')
  assert.equal(filled.Product.src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpageproduct.mp4')
  assert.equal(filled.Thumbnail.src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/thumbnail.png')
  assert.equal(filled.Thumbnail.poster, filled.Thumbnail.src)
  assert.equal(filled.Ad.src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpagead.mp4')
  assert.equal(filled.Explainer.src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/facelessstudio1.mp4')
  assert.equal(filled.Voiceover.src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/facelessstudio.mp4')
  const js = readFileSync(new URL('../lib/landing-page.js', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../home/landing-redesign.css', import.meta.url), 'utf8')
  assert.ok(!js.includes('hero-mq-lab'))
  assert.ok(!css.includes('.hero-mq-lab'))
})

test('showcase mixes formats and format cards stay blank-ready', () => {
  assert.equal(SHORTS_CARDS.length, 7)
  assert.ok(SHORTS_CARDS.every((c) => c.src && c.poster && c.category))
  assert.ok(!SHORTS_CARDS.some((c) => c.slug === 'listicles' || c.slug === 'documentary'))
  assert.equal(SHORTS_CARDS.find((c) => c.slug === 'long-form').src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpagelongform.mp4')
  assert.equal(SHORTS_CARDS.find((c) => c.slug === 'shorts').src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpageformatsshort.mp4')
  assert.equal(SHORTS_CARDS.find((c) => c.slug === 'ads').src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpageformatsad.mp4')
  assert.equal(SHORTS_CARDS.find((c) => c.slug === 'ugc').src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpageformatsugc.mp4')
  assert.equal(SHORTS_CARDS.find((c) => c.slug === 'explainers').src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/facelessstudio3.mp4')
  assert.equal(SHORTS_CARDS.find((c) => c.slug === 'product-videos').src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpageformatsproduct.mp4')
  assert.equal(SHORTS_CARDS.find((c) => c.slug === 'talking-head').src, 'https://pub-f40c956471ff49feab622906892ec527.r2.dev/landingpageformatstalkinghead.mp4')
  assert.equal(SHORTS_CARDS.filter((c) => !['long-form', 'shorts', 'ads', 'ugc', 'explainers', 'product-videos', 'talking-head'].includes(c.slug)).length, 0)
  assert.ok(SHOWCASE_CARDS.length >= 4)
  assert.ok(SHOWCASE_CARDS.every((c) => /videocarousel\d+\.mp4$/.test(c.src)))
  assert.ok(SHOWCASE_CARDS.every((c) => c.prompt && c.prompt.length > 12))
  assert.ok(SHOWCASE_CARDS.some((c) => c.category === 'AD'))
  assert.ok(SHOWCASE_CARDS.some((c) => c.category === 'UGC'))
  assert.ok(SHOWCASE_CARDS.some((c) => c.category === 'PRODUCT'))
  assert.equal(SHOWCASE_CARDS[0].category, 'DOCUMENTARY')
  assert.equal(SHORTS_PROMPTS.length, 8)
  assert.ok(SHORTS_PROMPTS.every((s) => s.length > 8 && /[a-zA-Z]$/.test(s)))
  assert.equal(HOW_PANEL_SRC, '')
})

test('hero pin transition is gone', () => {
  assert.ok(!html.includes('id="hero-pin"'))
  assert.ok(!html.includes('hero-dark-beat'))
  assert.ok(!html.includes('hero-pin-stage'))
  assert.ok(!html.includes('id="demo-hero"'))
  assert.ok(!html.includes('id="demo-video"'))
  const css = readFileSync(new URL('../home/landing-redesign.css', import.meta.url), 'utf8')
  assert.ok(!css.includes('--hero-pin-vh'))
  assert.ok(!css.includes('hero-pin-stage'))
})

test('landing keeps SEO, one H1, and the live page font', () => {
  assert.match(html, /<meta name="description"/)
  assert.equal((html.match(/<h1[\s>]/g) || []).length, 1)
  for (const id of ['how', 'connect-claude', 'pricing', 'faq']) {
    assert.ok(html.includes(`id="${id}"`), id)
  }
  assert.ok(html.includes('Your faceless YouTube empire starts here'))
  assert.ok(html.includes('Choose the plan'))
  assert.ok(html.includes('for you.'))
  assert.ok(html.includes('Generate a Video Now'))
  assert.ok(html.includes("font-family:'Bricolage Grotesque','Inter'"))
  assert.ok(html.includes('Bricolage+Grotesque'))
  assert.ok(html.includes('font-weight:800'))
})

test('landing reveal uses GSAP ScrollTrigger scrub instead of IntersectionObserver', () => {
  const reveal = readFileSync(new URL('../lib/landing-reveal.js', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../home/landing-redesign.css', import.meta.url), 'utf8')
  assert.ok(reveal.includes('scrub: 0.6'))
  assert.ok(reveal.includes('startAt(i === 0 ? 95 : 92)'))
  assert.ok(!reveal.includes('IntersectionObserver'))
  assert.ok(css.includes('.lp-sitehead'))
  assert.ok(css.includes('position:fixed'))
  assert.match(css, /\.lp-red h1,[\s\S]*font-family:Satoshi/)
  assert.ok(!css.includes('.lp-red.is-home .lp-sitehead'))
  assert.ok(css.includes('.lp-red .lp-sitehead.is-scrolled'))
  assert.match(css, /\.rv-clip,\s*\.rv-line/)
  assert.ok(css.includes('.lp-red .results .eyebrow'))
  assert.ok(css.includes('.formats-float .formats-mid'))
  assert.ok(css.includes('.mcp-panel::after{display:none}'))
  assert.ok(css.includes('.lp-red .comp-cta::before{display:none}'))
  assert.ok(css.includes('.final-box::before{display:none}'))
  assert.ok(!css.includes('.shorts-ico'))
  assert.ok(!css.includes('.shorts-lab'))
  assert.ok(!css.includes('margin-top:-18px'))
})

test('FAQ accordion closes the open item across both columns', () => {
  const js = readFileSync(new URL('../lib/landing-page.js', import.meta.url), 'utf8')
  assert.match(js, /if \(single\) bindFaqSingle\(grid\)\s+else bindFaqGroup\(grid\)/)
  assert.ok(!js.includes("grid.querySelectorAll('.faq-col').forEach((col) => bindFaqGroup(col))"))
})

test('live landing headings stay on the YouTube page', () => {
  assert.ok(html.includes('Your faceless YouTube empire starts here'))
  assert.ok(html.includes('AI long-form built for retention'))
  assert.ok(html.includes('Choose the plan <span class="accent">for you.</span>') || html.includes('Choose the plan'))
  assert.ok(html.includes('Claude AI video generator'))
})

test('formats carousel only advances from arrows', () => {
  const js = readFileSync(new URL('../lib/landing-page.js', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../home/landing-redesign.css', import.meta.url), 'utf8')
  const shorts = js.slice(js.indexOf('function mountShorts'), js.indexOf('function mountShowcase'))
  assert.ok(!shorts.includes('pointerenter'))
  assert.ok(!shorts.includes('setInterval'))
  assert.ok(shorts.includes("querySelector('[data-short-prev]')"))
  assert.ok(css.includes('.shorts-nav:hover{background:#FE0C30'))
  assert.ok(css.includes('.shorts-nav{'))
  assert.ok(!shorts.includes('shorts-meta'))
  assert.ok(!shorts.includes('shorts-lab'))
})

test('UGC row plays looping ugcad clips in the vertical cards', () => {
  const js = readFileSync(new URL('../lib/landing-page.js', import.meta.url), 'utf8')
  const css = readFileSync(new URL('../home/landing-redesign.css', import.meta.url), 'utf8')
  const attach = js.slice(js.indexOf('function attachUgcClip'), js.indexOf('function mountUgc'))
  assert.ok(attach.includes('v.loop = true'))
  assert.ok(attach.includes('v.autoplay = true'))
  assert.ok(attach.includes("v.setAttribute('muted', '')"))
  assert.ok(css.includes('object-fit:cover'))
  assert.ok(css.includes('.ugc-shot{') || css.includes('aspect-ratio:9/16'))
})

test('top-models copy is centered, heading wraps, and landing uses slots 1-10', () => {
  const css = readFileSync(new URL('../home/landing-redesign.css', import.meta.url), 'utf8')
  assert.match(css, /\.top-models-copy\{[\s\S]*?position:absolute[\s\S]*?left:50%[\s\S]*?top:50%[\s\S]*?transform:translate\(-50%,-50%\)/)
  assert.match(css, /\.lp-red\.is-home #connect-claude ~ #top-models h2\{[\s\S]*?white-space:normal;text-wrap:balance;text-align:center/)
  assert.ok(css.includes('.lp-red.is-home #top-models h2 .accent{display:block}'))
  assert.ok(css.includes('.top-models-tile[data-slot="10"]'))
  assert.ok(!css.includes('.top-models-tile[data-slot="11"]'))
  assert.ok(html.includes("font-family:'Bricolage Grotesque','Inter'"))
  assert.ok(!readFileSync(new URL('../lib/landing-page.js', import.meta.url), 'utf8').includes('videoeditor.png'))
  assert.ok(!css.includes('.hero-marquee:hover .hero-marquee-track'))
  assert.ok(!css.includes('.hero-marquee:focus-within .hero-marquee-track'))
})

test('announcement config and long-form demo start stay in one place', () => {
  assert.equal(LANDING_ANNOUNCE.key, 'announce_seedream5pro_v2')
  assert.equal(LANDING_ANNOUNCE.href, '/dashboard')
  assert.match(LANDING_ANNOUNCE.text, /Seedream 5.0 Pro/)
  assert.match(LANDING_ANNOUNCE.textMobile, /Thumbnail Generator/)
  assert.equal(LANDING_ANNOUNCE.cta, 'Try it now ›')
  assert.equal(LONGFORM_DEMO_START, 12)
})
