export const VIDSO_R2_BASE = 'https://pub-f40c956471ff49feab622906892ec527.r2.dev'
export const VIDSO_LOGO_URL = VIDSO_R2_BASE + '/vidso-logo.png'
export const CLAUDE_ICON_URL = VIDSO_R2_BASE + '/claude-ai-icon.webp'
export const YOUTUBE_LOGO_URL = VIDSO_R2_BASE + '/youtubelogo.png'
export const CLAUDE_CONNECTORS_URL = 'https://claude.ai/settings/connectors'
